### ISSUE TITLE
FID evaluation details

### ISSUE THREAD

**Issue by ZhaoyangLyu** [kpandey008/DiffuseVAE#7]
Hi, I have some questions about FID evaluations for CIFAR-10 and CelebA-64.
May I know how many images you generate to compute fid for CIFAR-10 and CelebA-64, respectively?
And which split of the CIFAR-10 and CelebA-64 datasets do you use to compute fid?
I am assuming that the training set of  CIFAR-10 (50,000 images), and the whole dataset of CelebA (202,599 images) are used to compute fid. Is that correct?

**Comment by kpandey008** [comment]
Hi,
For both CIFAR-10 and CelebA-64, the FID score computation is done using 50k samples. We used the torch-fidelity (https://github.com/toshas/torch-fidelity) package to compute the FID scores. I will make the samples used to compute the FID scores publicly available as well

**Comment by ZhaoyangLyu** [comment]
Thanks for your reply! That really helps!
I have two more questions. 
1. We need to resize the original images in CelebA to 64*64 before computing FID. Is that correct?
2. And do you think it is appropriate to use Inception Score to evaluate the generation quality for CelebA dataset?

**Comment by kpandey008** [comment]
1) Yeah we need to resize the original images to 64 x 64. FID is susceptible to the type of resizing used. We reported all our results by resizing the images to 64 x 64 using bilinear resizing.
2) Sure Inception score can be reported for CelebA-64 but I found previous work to only report FID so we do not report Inception score for this dataset.

**Comment by ZhaoyangLyu** [comment]
Thanks for your reponse!
